unit uPSI_Util;
{
This file has been generated by UnitParser v0.7, written by M. Knight
and updated by NP. v/d Spek and George Birbilis. 
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface
 
uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;
 
type 
(*----------------------------------------------------------------------------*)
  TPSImport_Util = class(TPSPlugin)
  public
    procedure CompileImport1(CompExec: TPSScript); override;
    procedure ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter); override;
  end;
 
 
{ compile-time registration functions }
procedure SIRegister_TUtil(CL: TPSPascalCompiler);
procedure SIRegister_Util(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_TUtil(CL: TPSRuntimeClassImporter);
procedure RIRegister_Util(CL: TPSRuntimeClassImporter);


implementation


uses
   Script_Util
  ;


(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_TUtil(CL: TPSPascalCompiler);
begin
  //with RegClassS(CL,'TOBJECT', 'TUtil') do
  with CL.AddClass(CL.FindClass('TOBJECT'), TUtil) do
  begin
    RegisterMethod('Function CurrToStr( Value : Currency) : string');
    RegisterMethod('Function IntToStr( Value : integer) : string');
    RegisterMethod('Function DiaSemana( Fecha : TDate) : TDiaSemana');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure SIRegister_Util(CL: TPSPascalCompiler);
begin
  CL.AddTypeS('TDiaSemana', '( dsLunes, dsMartes, dsMiercoles, dsJueves, dsVier'
   +'nes, dsSabado, dsDomingo )');
  SIRegister_TUtil(CL);
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure RIRegister_TUtil(CL: TPSRuntimeClassImporter);
begin
  with CL.Add(TUtil) do
  begin
    RegisterMethod(@TUtil.CurrToStr, 'CurrToStr');
    RegisterMethod(@TUtil.IntToStr, 'IntToStr');
    RegisterMethod(@TUtil.DiaSemana, 'DiaSemana');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_Util(CL: TPSRuntimeClassImporter);
begin
  RIRegister_TUtil(CL);
end;

 
 
{ TPSImport_Util }
(*----------------------------------------------------------------------------*)
procedure TPSImport_Util.CompileImport1(CompExec: TPSScript);
begin
  SIRegister_Util(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TPSImport_Util.ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter);
begin
  RIRegister_Util(ri);
end;
(*----------------------------------------------------------------------------*)
 
 
end.
