unit uPSI_Log;
{
This file has been generated by UnitParser v0.7, written by M. Knight
and updated by NP. v/d Spek and George Birbilis. 
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface
 
uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;
 
type 
(*----------------------------------------------------------------------------*)
  TPSImport_Log = class(TPSPlugin)
  public
    procedure CompileImport1(CompExec: TPSScript); override;
    procedure ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter); override;
  end;
 
 
{ compile-time registration functions }
procedure SIRegister_TLog(CL: TPSPascalCompiler);
procedure SIRegister_Log(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_TLog(CL: TPSRuntimeClassImporter);
procedure RIRegister_Log(CL: TPSRuntimeClassImporter);

implementation

uses
   Script_Log;

(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_TLog(CL: TPSPascalCompiler);
begin
  //with RegClassS(CL,'TOBJECT', 'TLog') do
  with CL.AddClass(CL.FindClass('TOBJECT'), TLog) do
  begin
    RegisterMethod('Procedure Mensaje( const mensaje : string)');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure SIRegister_Log(CL: TPSPascalCompiler);
begin
  SIRegister_TLog(CL);
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure RIRegister_TLog(CL: TPSRuntimeClassImporter);
begin
  with CL.Add(TLog) do
  begin
    RegisterMethod(@TLog.Mensaje, 'Mensaje');
  end;
end;

(*----------------------------------------------------------------------------*)
procedure RIRegister_Log(CL: TPSRuntimeClassImporter);
begin
  RIRegister_TLog(CL);
end;

 
 
{ TPSImport_Log }
(*----------------------------------------------------------------------------*)
procedure TPSImport_Log.CompileImport1(CompExec: TPSScript);
begin
  SIRegister_Log(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TPSImport_Log.ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter);
begin
  RIRegister_Log(ri);
end;
(*----------------------------------------------------------------------------*)
 
 
end.
